config/routes.rb
Karmy::Application.routes.draw do

  resources :posts
  resources :comments

  root :to => 'home#index'
  
  get "home/index"

  get "home/about"

  get "home/terms"

  get "home/contact"

  match '/auth/:provider/callback' => 'authentications#create'
  
  resources :authentications

  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users

  

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
	belongs_to :user
	attr_accessible :user_id, :provider, :uid, :image_url
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :content, :post_id
end

app/models/compliment.rb
class Compliment < Post
end

app/models/crush.rb
class Crush < Post
end

app/models/everything_else.rb
class EverythingElse < Post
end

app/models/hookup.rb
class Hookup < Post
end

app/models/humor.rb
class Humor < Post
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
  attr_accessible :accepted, :recipient_name, :recipient_email, :post_id, :sender_id, :token

  before_create :generate_token

  def generate_token
	  self.token = Digest::SHA1.hexdigest([Time.now, rand].join)
	end
end

app/models/network.rb
class Network < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :user_id, :category

   def add_or_update(user_id, omniauth)
  	education = omniauth['extra']['raw_info']['education']
  	work = omniauth['extra']['raw_info']['work']
 
  	
  	# Check to see if Network already exist, if not add them
  	work.each do |company|
  		Network.where(:name => company['employer']['name']).first_or_create(:user_id => user_id, :category => 'work') 
  	end

  	education.each do |edu|
  		Network.where(:name => edu['school']['name']).first_or_create(:user_id => user_id, :category => 'school')
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_one :invitation
  has_many :comments
  attr_accessible :content, :type, :user_id, :signature
end

app/models/rant.rb
class Rant < Post
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :authentications
  has_many :posts
  has_many :networks
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
  # attr_accessible :title, :body

  def apply_omniauth(omniauth)
  	#raise omniauth.to_yaml
  	self.email = omniauth.info.email if email.blank?
    name = omniauth.info.name.split(' ')
    self.first_name = name[0]
    self.last_name = name[1]
  	authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'], :image_url => omniauth['info']['image'])
  end

  def password_required?
    (authentications.empty? || !password.blank?) && super
  end

end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  # GET /authentications
  # GET /authentications.json
  def index
    @authentications = current_user.authentications if current_user

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authentications }
    end
  end


  # POST /authentications
  # POST /authentications.json
  def create
    omniauth = request.env['omniauth.auth']
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    network = Network.new
    if authentication
      network.add_or_update(authentication.user_id, omniauth)
      flash[:notice] = 'Signed in succesfully'
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = 'Authentication succesful'
      redirect_to authentications_url
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        network.add_or_update(user.id, omniauth)
        flash[:notice] = 'Signed in succesfully'
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url      
      end
  end


  # DELETE /authentications/1
  # DELETE /authentications/1.json
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy

    respond_to do |format|
      format.html { redirect_to authentications_url }
      format.json { head :no_content }
    end
  end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def terms
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    @post = Post.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        @invitation = Invitation.new(:sender_id => current_user.id,
                                    :post_id => @post.id,
                                    :recipient_email => params[:email])
        @invitation.save
        InvitationMailer.compliment_notification_email(@invitation, @post).deliver

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  	@image_url = @user.authentications.first.image_url

  end

  def edit
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authentications/_form.html.erb
<%= form_for(@authentication) do |f| %>
  <% if @authentication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

      <ul>
      <% @authentication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<h2>Sign In</h2>

<% if @authentications %>
  <% unless @authentications.empty? %>
    <p><strong>You can sign in to this account using:</strong></p>
    <div class="authentications">
      <% for authentication in @authentications %>
        <div class="authentication">
          <%= image_tag "https://raw.github.com/intridea/authbuttons/master/png/#{authentication.provider}_32.png", :size => "32x32" %>
          <div class="provider"><%= authentication.provider.titleize %></div>
          <div class="uid"><%= authentication.uid %></div>
          <%= link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove" %>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <p><strong>Add another service to sign in with:</strong></p>
<% else %>
  <p><strong>Sign in through one of these services:</strong></p>
<% end %>

<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "https://raw.github.com/intridea/authbuttons/master/png/facebook_64.png", :size => "64x64", :alt => "Facebook" %>
  Facebook
</a>

<a href="/auth/twitter" class="auth_provider">
  <%= image_tag "https://raw.github.com/intridea/authbuttons/master/png/twitter_64.png", :size => "64x64", :alt => "Twitter" %>
  Twitter
</a>
<div class="clear"></div>

app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @authentication.user_id %>
</p>

<p>
  <b>Provider:</b>
  <%= @authentication.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @authentication.uid %>
</p>


<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>